# Generated by Django 5.1.6 on 2025-02-19 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_expense_user_income_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense_tracker.place'),
        ),
    ]
