# Generated by Django 5.1.6 on 2025-02-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_income_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='place',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='place',
            new_name='source',
        ),
    ]
